Coticula.Web/Controllers/SolutionController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Coticula.Web.Models;

namespace Coticula.Web.Controllers
{ 
    public class SolutionController : Controller
    {
        private readonly CoticulaDbContext _db = new CoticulaDbContext();

        //
        // GET: /Solution/

        public ViewResult Index()
        {
            var results = _db.Results.Include(r => r.Verdict).Include(r => r.Solution.Language).Include(r => r.Solution.Problem);
            return View(results.ToList());
        }

        //
        // GET: /Solution/Details/5

        public ActionResult Details(int id, string format)
        {
            var result = _db.Results.Include(r => r.Solution.Language).Include(r => r.Solution.Problem).Include(r => r.Verdict).Single(r => r.Id == id);

            return View(result);
        }

        //
        // GET: /Solution/Edit/5
 
        public ActionResult Edit(int id)
        {
            var result = _db.Results.Find(id);
            ViewBag.VerdictId = new SelectList(_db.Verdicts, "Id", "Name", result.VerdictId);
            return View(result);
        }

        //
        // POST: /Solution/Edit/5

        [HttpPost]
        public ActionResult Edit(Result result)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(result).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VerdictId = new SelectList(_db.Verdicts, "Id", "Name", result.VerdictId);
            return View(result);
        }

        //
        // GET: /Solution/Delete/5
 
        public ActionResult Delete(int id)
        {
            var result = _db.Results.Find(id);
            return View(result);
        }

        //
        // POST: /Solution/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            var result = _db.Results.Find(id);
            _db.Results.Remove(result);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Coticula.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Solutions", "Index", "Solution")</li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

Coticula.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}